### ISSUE TITLE
Merge dependency PRs

### ISSUE THREAD

**Issue by FMGordillo** [pixelmanya/react-a11y-modal#10]
It would be awesome to patch this up

![image](https://user-images.githubusercontent.com/7970174/100299028-6e1aeb80-2f71-11eb-9a90-4feee0cfb71f.png)

**Comment by pixelmanya** [comment]
Hi @FMGordillo,

Yes, sounds like a good idea. Will do so very soon and keep you posted. 👍 

Cheers

**Comment by pixelmanya** [comment]
Everything is up-to-date now. Thanks for checking in!
